# Generated by Django 4.2.5 on 2023-09-30 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vacancy', models.CharField(max_length=128, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('salary', models.IntegerField(verbose_name='З/П (руб.месяц)')),
                ('organization', models.CharField(max_length=255, verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, verbose_name='Комментарий')),
                ('resume', models.FileField(upload_to='', verbose_name='Резюме')),
                ('number_phone', models.CharField(max_length=12, verbose_name='Номемер телефона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
