# Generated by Django 4.2.5 on 2023-10-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_resume_vacation_id_alter_resume_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(upload_to='resumes/', verbose_name='Резюме'),
        ),
    ]
