# Generated by Django 4.2.3 on 2023-08-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0003_advertisement_user_alter_advertisement_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='img',
            field=models.ImageField(default='', upload_to='advertisements/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
